common:
  daemonize: false
  log_media: stdout
  log_level: info

api:
  server:
    listen_uri: 0.0.0.0:8080
    tls: false
    # trusted_ips:        # comment out or set to ["0.0.0.0/0"] if needed

crowdsec:
  acquisition:
    - /etc/crowdsec/acquis.yaml