apiVersion: v1
kind: Service
metadata:
  name: deepfake-service
  namespace: deepfake-namespace
spec:
  selector:
    app: deepfake-service
  ports:
    - name: http  
      port: 8000
      protocol: TCP
      targetPort: 8080

---

apiVersion: v1
kind: Deployment
metadata:
  name: deepfake-rest-service
  namespace: deepfake-namespace
spec:
  selector:
    matchLabels:
      app: deepfake-app-service
  template:
    metadata:
      labels:
        app: deepfake-service
    spec:
      volumes:
        name: nginx-configuration-map
        configMap:
          name: nginx-config-map
          items:  
            - key: nginx.conf
              subPath: nginx.conf

      initContainer: 
        - name: nginx-server
          volumeMounts:
            - name: nginx-config-map
              subPath: nginx.conf
              path: /etc/nginx/
          image: nginx:latest
          ports:
            - containerPort: 8080
              protocol: TCP
          imagePullPolicy: IfNotPresent

      containers:
        - name: rest-service
          image: ${SERVICE_DOCKER_IMAGE}
          ports:
            - port: 8060
              protocol: TCP

          imagePullPolicy: IfNotPresent

          envFrom:
            - configMapRef:
              - name: inference-config-map

            - secretRef:
              - name: inference-config-map
            
          livenessProbe:
            command: curl -X GET -f http://localhost:8060/healthcheck
            initialDelaySeconds: 20
