download_url: https://galaxy.ansible.com/api/v3/plugin/ansible/content/published/collections/artifacts/cub_oit_pe-consul-0.2.0.tar.gz
format_version: 1.0.0
name: consul
namespace: cub_oit_pe
server: https://galaxy.ansible.com/api/
signatures: []
version: 0.2.0
version_url: /api/v3/plugin/ansible/content/published/collections/index/cub_oit_pe/consul/versions/0.2.0/
